### PR TITLE
Master  more info

### PR DESCRIPTION
**Pull request by thezoggy**

### CODE REVIEW

**Comment by Safihre** [comment]
https://github.com/sabnzbd/sabbuild/releases/tag/2.1.0-beta1-thezoggy-pr1

**Comment by Safihre** [comment]
https://ci.appveyor.com/project/Safihre/sabbuild

**Comment by thezoggy** [comment]
looks like it worked :)
img

**Comment by thezoggy** [comment]
now the whole version field..  we would need to always provide the `#.#.#.#` format otherwise none of the stuff gets added to the file. and since we dont do semver I just have it hardcoded to `0.0.0.0` for now.. since we do the version in the product/description.  

now not sure if you've looked at the changes but I added a few `TODO:` lines of stuff to talk about.. since I didn't want to rewrite code/remove stuff and not know if it breaks anything. 

also I noticed that we only put the icon to the sabnzbd.exe, do we want to put the icon to the other binaries (maybe a different one since we dont want to confuse people on running the wrong one)?

**Pull request merged**
