### PR TITLE
Exclude pdb/difflib/calendar to save even more space per compile.

### PR DESCRIPTION
**Pull request by thezoggy**

### CODE REVIEW

**Comment by thezoggy** [comment]
could have excluded a few more but being cautious, these are ones that py2exe wiki even recommends and I confirm that we do not use them by searching across the whole project .py files for any references. looks like we should save another 100kb easily.

**Comment by Safihre** [comment]
I tried dat before, but barely saves anything. But why not 👍 

With the Appveyor script you should be able to setup a build-setup quickly, since you don't need both 32 and 64 bit, there's no need for a virtualenv and just running `package.py` will do the trick. Just get NSIS!

**Comment by Safihre** [comment]
`calendar` was needed after all. 
```
Traceback (most recent call last):
  File "SABnzbd.py", line 54, in <module>
  File "cherrypy\__init__.pyo", line 66, in <module>
  File "cherrypy\_cperror.pyo", line 128, in <module>
  File "cherrypy\lib\httputil.pyo", line 11, in <module>
  File "email\utils.pyo", line 32, in <module>
  File "email\_parseaddr.pyo", line 16, in <module>
ImportError: No module named calendar
```

**Comment by thezoggy** [comment]
interesting, wonder why calendar is being used there...   did that show up during the build ?

**Comment by Safihre** [comment]
No, just starting sabnzbd.exe would fail and write a log.

**Pull request merged**
